import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'os';
import chalk from 'chalk';
import ora from 'ora';
import { createContext, runAllChecks } from '../checks/index.js';
import { calculateHealthScore } from '../utils/health.js';
import { execCommand } from '../utils/exec.js';
import { redactSecrets } from '../utils/redact.js';

export interface ReportOptions {
  cwd?: string;
  output?: string;
}

export async function reportCommand(options: ReportOptions = {}): Promise<number> {
  const cwd = options.cwd || process.cwd();
  const spinner = ora('Generating diagnostic report...').start();

  const context = await createContext(cwd, false);
  const results = await runAllChecks(context);
  const score = calculateHealthScore(results);

  // Collect environment info
  const nodeVersion = process.version;
  const osInfo = `${os.type()} ${os.release()} (${os.arch()})`;

  const gitRes = await execCommand('git', ['--version']);
  const gitVersion = gitRes.code === 0 ? gitRes.stdout : 'Not installed';

  let pmInfo = 'npm';
  if (context.pkg?.packageManager) {
    pmInfo = context.pkg.packageManager;
  }

  const pkgName = context.pkg?.name || 'Unnamed Project';
  const pkgVer = context.pkg?.version || '0.0.0';
  const dateStr = new Date().toUTCString();

  const statusEmoji = {
    success: '✅ PASS',
    warning: '⚠️ WARN',
    error: '❌ FAIL',
    info: 'ℹ️ INFO',
    skipped: '⚪ SKIP',
  };

  const mdLines = [
    `# 🩺 Tern Environment Diagnostic Report`,
    ``,
    `> Generated automatically by [Tern](https://github.com/tern-tools/tern) on **${dateStr}**`,
    ``,
    `## 📊 Project Health: ${score.percentage}% (${score.rating})`,
    ``,
    `- **Passed:** ${score.passed}`,
    `- **Warnings:** ${score.warnings}`,
    `- **Errors:** ${score.errors}`,
    `- **Total Checks:** ${score.total}`,
    ``,
    `## 🖥️ System & Environment Details`,
    ``,
    `| Property | Value |`,
    `| --- | --- |`,
    `| **Project** | \`${pkgName}@${pkgVer}\` |`,
    `| **OS** | \`${osInfo}\` |`,
    `| **Node.js** | \`${nodeVersion}\` |`,
    `| **Package Manager** | \`${pmInfo}\` |`,
    `| **Git** | \`${gitVersion}\` |`,
    ``,
    `## 📋 Detailed Diagnostic Results`,
    ``,
    `| Status | Category | Check | Details |`,
    `| :---: | :--- | :--- | :--- |`,
  ];

  if (score.categories) {
    mdLines.push(``);
    mdLines.push(`### Category Breakdown`);
    mdLines.push(``);
    mdLines.push(`| Category | Health | Status |`);
    mdLines.push(`| :--- | :---: | :--- |`);
    for (const [catName, catHealth] of Object.entries(score.categories)) {
      if (!catHealth.applicable) continue;
      const statusText =
        catHealth.errors > 0
          ? '❌ Issues Detected'
          : catHealth.warnings > 0
            ? '⚠️ Warnings'
            : '✅ Healthy';
      mdLines.push(`| **${catName}** | ${catHealth.percentage}% | ${statusText} |`);
    }
  }

  for (const r of results) {
    const emoji = statusEmoji[r.status] || '❓';
    const cleanMsg = redactSecrets(r.message.replace(/\|/g, '\\|'));
    mdLines.push(`| ${emoji} | \`${r.category}\` | **${r.name}** | ${cleanMsg} |`);
  }

  const issuesWithHints = results.filter(
    (r) => (r.status === 'error' || r.status === 'warning') && r.hint
  );
  if (issuesWithHints.length > 0) {
    mdLines.push(``);
    mdLines.push(`## 💡 Recommended Remediation Steps`);
    mdLines.push(``);
    for (const item of issuesWithHints) {
      mdLines.push(`- **${item.name}**: ${redactSecrets(item.hint!)}`);
    }
  }

  mdLines.push(``);
  mdLines.push(`---`);
  mdLines.push(`*Report generated by \`tern report\`. Ready to paste into GitHub Issues.*`);
  mdLines.push(``);

  const markdownContent = mdLines.join('\n');
  spinner.stop();

  if (options.output) {
    const outPath = path.isAbsolute(options.output)
      ? options.output
      : path.join(cwd, options.output);
    await fs.writeFile(outPath, markdownContent, 'utf8');
    console.log(
      chalk.green(`\n✓ Diagnostic report successfully saved to ${chalk.bold(outPath)}\n`)
    );
  } else {
    console.log(chalk.bold('\n--- Markdown Report (Copy & Paste below) ---\n'));
    console.log(markdownContent);
    console.log(
      chalk.dim('\nTip: Run "tern report -o tern-report.md" to save directly to a file.\n')
    );
  }

  return 0;
}
